# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_auto_20170818_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
