# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_auto_20170818_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='precio',
            field=models.DecimalField(blank=True, decimal_places=4, default=7, max_digits=10),
        ),
    ]
