# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=250)),
                ('apellidos', models.CharField(max_length=250)),
                ('titulo', models.TextField()),
                ('grado', models.TextField()),
                ('lugar_trabajo', models.TextField()),
            ],
        ),
    ]
