# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 17:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0003_veterinario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='tratamiento',
            name='vete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.Veterinario'),
        ),
        migrations.AddField(
            model_name='vacuna',
            name='descripcion',
            field=models.TextField(default=-1.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solicitd',
            name='vacuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Vacuna'),
        ),
        migrations.AddField(
            model_name='solicitd',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atencion.Veterinario'),
        ),
    ]
