# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.CharField(max_length=200),
        ),
    ]
