# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0002_auto_20161231_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('codigomedico', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.CharField(max_length=200)),
                ('fecha_contratacion', models.DateField()),
                ('horario', models.TextField()),
            ],
        ),
    ]
