# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ponente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('dni', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('grados', models.TextField()),
                ('titulos', models.TextField()),
                ('lugares_trabajo', models.TextField()),
            ],
        ),
    ]
