# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 04:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0003_auto_20170816_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='cantidad_butacas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sala',
            name='butacas',
            field=models.ManyToManyField(blank=True, to='sala.Butaca'),
        ),
    ]
