# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20170818_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='cantidad',
            field=models.CharField(max_length=4),
        ),
    ]
