# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atencion', '0001_initial'),
        ('mascota', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mascota',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='atencion.Persona'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='tratamiento',
            field=models.ManyToManyField(to='atencion.Tratamiento'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(to='atencion.Vacuna'),
        ),
    ]
