# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20161231_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='tratamiento',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='vacuna',
        ),
    ]
