# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='numero_paginas',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
