# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-06 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('editorial', models.CharField(max_length=70)),
                ('fecha_publicacion', models.DateField()),
            ],
        ),
    ]
