# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20170818_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_colaborador',
            field=models.BooleanField(default=True),
        ),
    ]
