# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='butacas',
            field=models.ManyToManyField(blank=True, to='sala.Butaca'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='pelicula',
            field=models.ManyToManyField(blank=True, to='sala.Pelicula'),
        ),
    ]
