# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('duracion', models.CharField(max_length=50)),
                ('director', models.CharField(max_length=255)),
                ('elenco', models.TextField()),
                ('grupo_produccion', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('idioma', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('distribuidora', models.CharField(max_length=70)),
                ('categoria_pelicula', models.ManyToManyField(to='pelicula.CategoriaPelicula')),
            ],
            options={
                'ordering': ['fecha_estreno'],
            },
        ),
        migrations.CreateModel(
            name='RestriccionesPelicula',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='restricciones_pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pelicula.RestriccionesPelicula'),
        ),
    ]
