# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelicula', '0003_pelicula_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='nombre_alterno',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
